use_frameworks!

platform :ios, '9.0'

target 'ColorGetFramework_Example' do
  pod 'ColorGetFramework', :path => '../'

  target 'ColorGetFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
